<a href="https://colab.research.google.com/github/Hackerifyouwant/Deep_learning/blob/master/pandas/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#Numpy
##author Hackerifyouwant
###2018/4/28



In [50]:
import numpy as np



a = np.array([[0,1,2],[3,4,5],[6,7,8]], dtype=np.float32)
print("Array with float32")
print(a)
print()

persontype=np.dtype({
    'names': ['name', 'age', 'weight'], 
    'formats': [np.str_, np.int16, np.float32]
})
# customize the type of array
b = np.array([("Zhang", 32, 75.5), ("Wang", 24, 65.2)], dtype=persontype)
print("Array with customized type")
print(b)
print()

x = np.array([[1,2.0],[0,0],(1+1j,3+1j)])
print("Simple array")
print(x)
print()

c=np.zeros((2,3))
print("Zero Matrix with 2 by 3")
print(c)
print()

d=np.arange(2, 3, 0.1)
print("Array which value between 2 and 3 seperated 0.1")
# 所有數值介在2～3之間，間隔0.1
print(d)
print()

e=np.linspace(1., 4., 6)
print("Array which value between 1 and 4 divide into 5 part")
# 所有數值介在1到4之間，評分切成6個點
print(e)

f=np.indices((6, 3))
print("Matrix with 6 by 3 and it Transposed matrix")
print(f)
print()

g=np.array([range(i, i + 3) for i in [2, 4, 6]])
print("The Matrix start with array[0] and plus three time in one colume")
print(g)
print()

h=np.array([0, 1, 2])
i=np.tile(h,3)

print("Repeat the same array three time")
print(i)
print()

j=np.tile(np.array([[1,2],[6,7]]),2)
print("Repeat the same array two time")
print(j)
print()

k=np.tile(np.array([[1,2],[6,7]]),(2,2))
print("Repeat the same array four time")
print(k)
print()

ar=np.arange(5); 
l=ar[::-1]
print("Rotate the array")
print(l)
print()


Array with float32
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

Array with customized type
[('', 32, 75.5) ('', 24, 65.2)]

Simple array
[[1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j]
 [1.+1.j 3.+1.j]]

Zero Matrix with 2 by 3
[[0. 0. 0.]
 [0. 0. 0.]]

Array which value between 2 and 3 seperated 0.1
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]

Array which value between 1 and 4 divide into 5 part
[1.  1.6 2.2 2.8 3.4 4. ]
Matrix with 6 by 3 and it Transposed matrix
[[[0 0 0]
  [1 1 1]
  [2 2 2]
  [3 3 3]
  [4 4 4]
  [5 5 5]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]]]

The Matrix start with array[0] and plus three time in one colume
[[2 3 4]
 [4 5 6]
 [6 7 8]]

Repeat the same array three time
[0 1 2 0 1 2 0 1 2]
Repeat the same array two time
[[1 2 1 2]
 [6 7 6 7]]
Repeat the same array four time
[[1 2 1 2]
 [6 7 6 7]
 [1 2 1 2]
 [6 7 6 7]]
rotate the array
[4 3 2 1 0]


#Pandas
##author Hackerifyouwant
###2018/4/26

In [0]:
import pandas as pd
import numpy as np

def output(obj):
  print(obj,obj.values,obj.index)


sdata={'a':1000,'b':2000,'c':3000,'d':4000}
obj=pd.Series(sdata)
output(obj)

obj2=pd.Series([4,7,5,6],index=['a','b','c','d'])
output(obj2*2)

np1=np.exp(obj2)
print(np1)

print('b' in obj2)

sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon':16000, 'Utah': 5000}
obj3=pd.Series(sdata)
output(obj3)

states=['California', 'Ohio', 'Oregon', 'Texas']
obj4=pd.Series(sdata,index=states)
output(obj4)

pd.isnull(obj4)


pd.notnull(obj4)

obj4.isnull()

a    1000
b    2000
c    3000
d    4000
dtype: int64 [1000 2000 3000 4000] Index(['a', 'b', 'c', 'd'], dtype='object')
a     8
b    14
c    10
d    12
dtype: int64 [ 8 14 10 12] Index(['a', 'b', 'c', 'd'], dtype='object')
a      54.598150
b    1096.633158
c     148.413159
d     403.428793
dtype: float64
True
Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64 [35000 71000 16000  5000] Index(['Ohio', 'Texas', 'Oregon', 'Utah'], dtype='object')


#Dataframe
##author Hackerifyouwant
###2018/4/27

In [51]:
import pandas as pd
import numpy as np

def output(obj):
  print(obj,obj.values,obj.index)
  
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 
        'year': [2000, 2001, 2002, 2001, 2002, 2003], 
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)
output(frame)

frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], 
                      index=['one', 'two', 'three', 'four', 'five', 'six'])

frame2.year
output(frame2)
frame2.loc['three']


output(frame2)

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2 [['Ohio' 2000 1.5]
 ['Ohio' 2001 1.7]
 ['Ohio' 2002 3.6]
 ['Nevada' 2001 2.4]
 ['Nevada' 2002 2.9]
 ['Nevada' 2003 3.2]] RangeIndex(start=0, stop=6, step=1)
       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN [[2000 'Ohio' 1.5 nan]
 [2001 'Ohio' 1.7 nan]
 [2002 'Ohio' 3.6 nan]
 [2001 'Nevada' 2.4 nan]
 [2002 'Nevada' 2.9 nan]
 [2003 'Nevada' 3.2 nan]] Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')
       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN [[2000 'Ohio' 1.5 nan]
 [2001 'Ohio' 1.7 nan]
 [2002 'Ohio' 3

##上傳python檔案到colab

In [52]:
!curl -O https://raw.githubusercontent.com/Hackerifyouwant/Ubuntu/master/decode/base64decode.py
!ls


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   114  100   114    0     0    497      0 --:--:-- --:--:-- --:--:--   497
base64decode.py  sample_data
